spring.security.oauth2.client.registration.google.client-id=//cloud_client_id
spring.security.oauth2.client.registration.google.client-secret=//google_client_secret
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://example
